
service: java-lambda-student-profile

provider:
  name: aws
  runtime: java8
  profile: ${opt:profile, 'uvsy-sls-dev'}
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'sa-east-1'}
  deploymentBucket: ${self:provider.stage}.${self:provider.region}.universy.serverless.deploys
  deploymentPrefix: ${self:provider.region}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "cognito-idp:GetUser"
        - "cognito-idp:UpdateUserAttributes"
      Resource: "*"
  environment:
    STAGE: ${self:provider.stage}
    CLIENT_ID: ${ssm:/${self:provider.stage}/cognito/clients/universy_mobile_client_id~true}
    AWS_COGNITO_REGION: ${ssm:/${self:provider.stage}/cognito/region~true}

package:
  artifact: build/distributions/${self:service}-1.0.zip

functions:
  get:
    name: ${self:provider.stage}-${self:service}-get
    handler: com.universy.student.profile.StudentProfileGetHandler

  post:
    name: ${self:provider.stage}-${self:service}-post
    handler: com.universy.student.profile.StudentProfilePostHandler
