
service: java-lambda-student-data # NOTE: update this with your service name

provider:
  name: aws
  runtime: java8
  profile: serverless
  stage: ${opt:stage, 'dev'}
  region: sa-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:GetItem"
        - "dynamodb:Query"
        - "dynamodb:UpdateItem"
        - "dynamodb:ListStreams"
        - "dynamodb:GetRecords"
      Resource: "*"
  environment:
    STAGE: ${self:provider.stage}

package:
  artifact: build/distributions/${self:service}-1.0.zip

functions:
  java-lambda-student-data-retriever:
    name: ${self:provider.stage}-${self:service}-retriever
    handler: com.universy.student.data.RetrieverHandler

  java-lambda-student-data-writer:
    name: ${self:provider.stage}-${self:service}-writer
    handler: com.universy.student.data.WriterHandler

