
service: java-lambda-student-profile # NOTE: update this with your service name

provider:
  name: aws
  runtime: java8
  profile: serverless
  stage: ${opt:stage, 'dev'}
  region: sa-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:GetItem"
        - "dynamodb:Query"
        - "dynamodb:UpdateItem"
        - "dynamodb:ListStreams"
        - "dynamodb:GetRecords"
      Resource: "*"
  environment:
    STAGE: ${self:provider.stage}

package:
  artifact: build/distributions/${self:service}-1.0.zip

functions:
  get:
    name: ${self:provider.stage}-${self:service}-get
    handler: com.universy.student.profile.StudentProfileGetHandler

  put:
    name: ${self:provider.stage}-${self:service}-put
    handler: com.universy.student.profile.StudentProfilePutHandler

