Resources:
  get:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./build/run
      Handler: com.universy.student.profile.StudentProfileGetHandler
      Runtime: java8
      MemorySize: 512
      Timeout: 300
      Environment:
        Variables:
          STAGE: dev
          CLIENT_ID: client
          AWS_COGNITO_REGION: us-east-1

  post:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./build/run
      Handler: com.universy.student.profile.StudentProfilePostHandler
      Runtime: java8
      MemorySize: 512
      Timeout: 300
      Environment:
        Variables:
          STAGE: dev
          CLIENT_ID: client
          AWS_COGNITO_REGION: us-east-1